# Linux-Only Test Configuration
# Focused testing for Linux environments

platforms:
  - name: linux
    base_image: ubuntu:22.04
    architectures: [amd64, arm64]
    zig_target_map:
      amd64: x86_64-linux-gnu
      arm64: aarch64-linux-gnu
    features:
      - epoll
      - unix_sockets
      - systemd_socket_activation
      - netlink_sockets
    build_options:
      - "-Dtarget-glibc=2.31"
      - "-Dunixsock=true"

test_suites:
  linux_specific:
    timeout: 120
    tests:
      - epoll-performance-test
      - unix-socket-test
      - systemd-activation-test
      - netlink-test
      - cgroup-limits-test
  
  glibc_compatibility:
    timeout: 60
    tests:
      - glibc-version-test
      - dynamic-linking-test
      - locale-support-test

distributions:
  - ubuntu:20.04  # glibc 2.31
  - ubuntu:22.04  # glibc 2.35
  - debian:11     # glibc 2.31
  - debian:12     # glibc 2.36
  - centos:8      # glibc 2.28
  - fedora:38     # glibc 2.37

timeouts:
  build: 300
  test: 120
  cleanup: 30
  global: 900